# Generated by Django 5.2.16 on 2026-07-17 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("enrollments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("answer_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("evaluating", "Evaluating"),
                            ("awaiting_review", "Awaiting review"),
                            ("graded", "Graded"),
                            ("remediation", "Remediation"),
                            ("needs_support", "Needs teacher support"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="enrollments.enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="AIGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("suggested_score", models.PositiveSmallIntegerField()),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("strengths", models.JSONField(default=list)),
                ("mistakes", models.JSONField(default=list)),
                ("feedback", models.TextField()),
                ("remediation", models.TextField(blank=True)),
                ("teacher_review_required", models.BooleanField(default=True)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_grade",
                        to="assessments.attempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("final_score", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("confirmed", "Confirmed"),
                            ("overridden", "Overridden"),
                        ],
                        default="provisional",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_decision",
                        to="assessments.attempt",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("explanation", "Explanation"),
                            ("code_writing", "Code writing"),
                            ("debugging", "Debugging"),
                            ("reflection", "Reflection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("max_score", models.PositiveSmallIntegerField(default=100)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lesson_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.lessonversion",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="attempt",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="assessments.question",
            ),
        ),
        migrations.CreateModel(
            name="ReviewQueueItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_item",
                        to="assessments.attempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RubricVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("criteria", models.JSONField(default=list)),
                ("total_score", models.PositiveSmallIntegerField(default=100)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_rubrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubrics",
                        to="assessments.question",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "question", "attempt_number"),
                name="unique_attempt_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempt_number__gte", 1), ("attempt_number__lte", 3)
                ),
                name="attempt_number_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="rubricversion",
            constraint=models.UniqueConstraint(
                fields=("question", "version_number"), name="unique_rubric_version"
            ),
        ),
    ]
