# Generated by Django 5.2.16 on 2026-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="aigrade",
            constraint=models.CheckConstraint(
                condition=models.Q(("suggested_score__lte", 100)), name="ai_score_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="aigrade",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="ai_confidence_range",
            ),
        ),
    ]
