# Generated by Django 5.2.16 on 2026-07-18 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_alter_question_question_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aigrade",
            name="errors",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="aigrade",
            name="recommended_action",
            field=models.CharField(
                choices=[
                    ("advance", "Advance"),
                    ("remediate", "Remediate"),
                    ("review", "Review"),
                ],
                default="review",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="aigrade",
            name="requires_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aigrade",
            name="score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="is_objective",
            field=models.BooleanField(
                default=False,
                help_text="Allow high-confidence AI results to be auto-confirmed for this question.",
            ),
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appeals",
                        to="assessments.attempt",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_assessment_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("ai_graded", "AI graded"),
                            ("auto_confirmed", "Automatically confirmed"),
                            ("review_requested", "Manual review requested"),
                            ("manually_confirmed", "Manually confirmed"),
                            ("overridden", "Overridden"),
                            ("appealed", "Appealed"),
                            ("appeal_resolved", "Appeal resolved"),
                            ("progression_updated", "Progression updated"),
                        ],
                        max_length=24,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_events",
                        to="assessments.attempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_review",
                        to="assessments.attempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.TextField()),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                ("code_language", models.CharField(blank=True, max_length=40)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not applicable"),
                            ("queued", "Queued"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("unavailable", "Sandbox unavailable"),
                        ],
                        default="not_applicable",
                        max_length=20,
                    ),
                ),
                ("execution_result", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission",
                        to="assessments.attempt",
                    ),
                ),
            ],
        ),
    ]
