# Generated by Django 5.2.16 on 2026-07-18 12:42

import ai_engine.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_aigrade_errors_aigrade_recommended_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="answer_text",
            field=ai_engine.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="submission",
            name="answer_text",
            field=ai_engine.fields.EncryptedTextField(),
        ),
    ]
