# Generated by Django 5.2.16 on 2026-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0002_aijob_generation_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("course_generation", "Course generation"),
                    ("grading", "Grading"),
                    ("project_grading", "Final project grading"),
                    ("translation", "Translation"),
                ],
                max_length=30,
            ),
        ),
    ]
