# Generated by Django 5.2.16 on 2026-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(max_length=190, unique=True),
        ),
    ]
