# Generated by Django 5.2.16 on 2026-07-18 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_lessonartifact_artifact_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("brief", models.TextField()),
                ("objectives", models.JSONField(default=list)),
                ("requirements", models.JSONField(default=list)),
                ("deliverables", models.JSONField(default=list)),
                ("rubric", models.JSONField(default=list)),
                ("estimated_hours", models.PositiveSmallIntegerField(default=8)),
                ("ai_generated", models.BooleanField(default=False)),
                ("teacher_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_project",
                        to="courses.courseversion",
                    ),
                ),
            ],
        ),
    ]
