# Generated by Django 5.2.16 on 2026-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_finalproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonartifact",
            name="ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lessonartifact",
            name="teacher_approved",
            field=models.BooleanField(default=True),
        ),
    ]
