# Generated by Django 5.2.16 on 2026-07-20 07:27

import ai_engine.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_lessonartifact_ai_generated_and_more"),
        ("enrollments", "0002_studentprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonartifact",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("video_embed", "Video embed"),
                    ("image", "Image"),
                    ("simulation_link", "Simulation link"),
                    ("code_example", "Code example"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="LessonFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_feedback",
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "lesson_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_feedback",
                        to="courses.lessonversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "lesson_version"),
                        name="unique_lesson_feedback_per_enrollment",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", ai_engine.fields.EncryptedTextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("evaluating", "Being reviewed"),
                            ("reviewed", "Reviewed"),
                            ("failed", "Review unavailable"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("feedback", models.TextField(blank=True)),
                ("remediation", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_submissions",
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "final_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="courses.finalproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("final_project", "enrollment"),
                        name="unique_final_project_submission_per_enrollment",
                    )
                ],
            },
        ),
    ]
